[#55] 상품 수정 Admin 기능 추가
f-lab-edu/star-dabang pull request #58
Opened 2021-04-14 14:03 UTC by 99gaga

### OptionUpdateCommand 클래스 추가
- 유동적으로 수정할 값만 업데이트 하기위해서 null 체크를 하지 않았습니다. 그래서 서비스에서 값이 있는 부분에 대해서만 유효성을 검증하도록 구현하였습니다.

### ProductAdminService `validProduct` 메소드 추출
- 상품을 새로 등록하거나 수정할 때 Product에 유효성 검증에 대하여 공통되기에 메소드로 추출하였고 카테고리 유효성을 확인하는 부분에서 수정할 때는 CategoryId가 null일 수도 있기 때문에 wrapper 타입으로 체크를 해주었습니다.

### MybatisProductRepository `saveProductOption` 메소드 추출
- 상품을 새로 등록할 때 옵션을 함께 저장시켜주는 로직을 옵션만 따로 저장할 때와 공통되기에 메소드로 추출하였습니다.

### 상품에서 삭제하는 옵션 예외처리
- 삭제할 옵션과 삭제된 옵션의 개수를 비교하여 예외를 처리해주었습니다.

### 상품에서 추가되는 옵션 예외처리
- 만약 같은 옵션이 추가되는 경우에 대해서 중복키 예외가 발생하므로 `productRepository.save(product)`와 함께 예외를 잡아주었습니다.

### 상품의 기존 옵션을 수정하는 경우 예외처리
- 같은 옵션이라도 수정되는 옵션의 quantity가 다른 부분이기 때문에 optionId를 List형태로 만들어서 상품의 기존 옵션들에 포함이 되는 값인지 확인해주었습니다.

2021-04-15 03:31 UTC, f-lab-dev commented on src/main/java/dabang/star/cafe/application/ProductAdminService.java
> +            throw new DuplicatedException(e.getCause().getMessage());
여기는 그냥 e를 던져줘도 좋을 것 같네요~

2021-04-16 02:13 UTC, f-lab-dev commented on src/main/java/dabang/star/cafe/application/exception/DuplicatedException.java
> +        super(cause.getCause().getMessage());
살짝 중복된 리뷰이긴 하지만 우리가 추후 예외를 만났을때 stacktrace가 어떻게 생겼을지 고민해보시면 좋을 것 같네요~

2021-04-18 02:14 UTC, f-lab-dev approved these changes

2021-04-18 02:15 UTC, f-lab-dev requested changes

2021-04-18 02:15 UTC, f-lab-dev commented on src/main/java/dabang/star/cafe/application/exception/DuplicatedException.java
> +        super(cause.getCause().getMessage(), cause);
이 부분도 `cause.getCause()`가 null일 가능성을 고려해야겠네요~

2021-04-20 02:27 UTC, f-lab-dev approved these changes

2021-04-20 15:55 UTC, zeroooooowest commented on src/main/java/dabang/star/cafe/application/ProductAdminService.java
> +        List<Long> optionId = productData.getOptions().stream().map(ProductOptionData::getOptionId).collect(Collectors.toList());
```java
Set<Long> optionId = productData.getOptions().stream()
                .map(ProductOptionData::getOptionId)
                .collect(Collectors.toSet());
```

List 의 contains 메서드는 O(N) 시간복잡도라 O(1)을 기대할 수 있는 Set은 어떨까요?

2021-04-20 16:44 UTC, zeroooooowest commented on src/main/java/dabang/star/cafe/application/ProductAdminService.java
> +        });
```java
Set<Long> optionIdSet = productData.getOptions().stream()
                .map(ProductOptionData::getOptionId)
                .collect(Collectors.toSet());
```

List 의 contains 메서드는 O(N) 시간복잡도라 O(1)을 기대할 수 있는 Set은 어떨까요?

2021-04-21 00:07 UTC, 99gaga commented on src/main/java/dabang/star/cafe/application/ProductAdminService.java
> +        });
좋은 생각 같습니다😀

2021-04-21 03:12 UTC, zeroooooowest approved these changes

2021-04-21 12:17 UTC, 99gaga commented
영서님의 시간복잡도 의견 제시로 자료구조형을 List -> Set 으로 변경하였습니다.
allowMultiQuries를 허용하여 다중 update하는 것은 결국엔 디비에서 여러 쿼리를 차례대로 수행하게 되며 SQL 주입 공격에 취약할 수 있어 현업에서는 사용되지 않으며 Oracle 같은 경우에는 멀티쿼리에 대한 속성이 없어 이런 문제들로 멀티쿼리 방식을 제거하였고 UPSERT 방식으로 업데이트를 진행하는 것으로 변경했습니다.

2021-04-22 01:22 UTC, f-lab-dev approved these changes

2021-04-22 11:43 UTC, merged